name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.11.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@v2
      with:
        julia-version: ${{ matrix.julia-version }}
        arch: x64

    - name: Build pkg
      uses: julia-actions/julia-buildpkg@v1

    - name: Run test
      uses: julia-actions/julia-runtest@v1

    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info